#
# ECE356 - Lab 3
# Fall 2020

# Modify this file to achieve the requirements listed in Part 4-1 of the Lab 3
# specifications.

# use yelp_db_small;
# ...
# DROP INDEX IF EXISTS ...
# CREATE INDEX ...
# ...
